<?php

/**
 * @file
 * Module for the micronews Entity - a starting point to create your own Entity
 * and associated administration interface
 */  


/**
 * Implement hook_entity_info().
 *
 * We define two entities here - the actual entity that will hold our domain
 * specific information and an entity that holds information about the different
 * types of entities. See here: http://drupal.org/node/977380 for a discussion on this
 * choice.
 */
function micronews_entity_info() {
  $return['micronews'] = array(
    'label' => t('MicroNews'),
    // The entity class and controller class extend the classes provided by the
    // Entity API
    'entity class' => 'micronews',
    'controller class' => 'micronewsController',
    'base table' => 'micronews',
    'fieldable' => TRUE,
    'entity keys' => array(
        'id' => 'micronews_id',
        'bundle' => 'type',
    ),
    // Bundles are defined by the micronews types below
    'bundles' => array(),
    // Bundle keys tell the FieldAPI how to extract information from the bundle objects
    'bundle keys' => array(
      'bundle' => 'type',
    ),
    'label callback' => 'entity_class_label',
    'uri callback' => 'entity_class_uri',
    'creation callback' => 'micronews_create',
    'access callback' => 'micronews_access',
    'module' => 'micronews',
    // The information below is used by the micronewsUIController (which extends the EntityDefaultUIController)
    'admin ui' => array(
      'path' => 'admin/content/micronews',
      'file' => 'micronews.admin.inc',
      'controller class' => 'micronewsUIController',
      'menu wildcard' => '%micronews',
    ),
  );
  // The entity that holds information about the entity types	  
  $return['micronews_type'] = array(
    'label' => t('Micronews Type'),
    'entity class' => 'micronewsType',
    'controller class' => 'micronewsTypeController',
    'base table' => 'micronews_type',
    'fieldable' => FALSE,
    'bundle of' => 'micronews',
    'exportable' => TRUE,
    'entity keys' => array(
      'id' => 'id',
      'name' => 'type',
      'label' => 'label',
    ),
    'access callback' => 'micronews_type_access',
    'module' => 'micronews',
    // Enable the entity API's admin UI.
    'admin ui' => array(
      'path' => 'admin/structure/micronews_types',
      'file' => 'micronews_type.admin.inc',
      'controller class' => 'micronewsTypeUIController',
    ),
  );

  return $return;
}


/**
 * Implements hook_entity_info_alter().
 *
 * We are adding the info about the micronews types via a hook to avoid a recursion
 * issue as loading the micronews types requires the entity info as well.
 *
 * @todo This needs to be improved
 */
function micronews_entity_info_alter(&$entity_info) {
  foreach (micronews_get_types() as $type => $info) {
    $entity_info['micronews']['bundles'][$type] = array(
      'label' => $info->label,
      'admin' => array(
        'path' => 'admin/structure/micronews_types/manage/%micronews_type',
        'real path' => 'admin/structure/micronews_types/manage/' . $type,
        'bundle argument' => 4,
        'access arguments' => array('administer micronews types'),
      ),
    );
  }
}
  

/**
 * Implements hook_permission().
 */
function micronews_permission() {
  // We set up permisssions to manage entity types, manage all entities and the
  // permissions for each individual entity
  $permissions = array(
    'administer micronews types' => array(
      'title' => t('Administer Micronews types'),
      'description' => t('Create and delete fields for micronews types, and set their permissions.'),
    ),
    'administer micronews' => array(
      'title' => t('Administer Micronews'),
      'description' => t('Edit and delete all micronews'),
    ),  
  );
  
  //Generate permissions per micronews 
  foreach (micronews_get_types() as $type) {
    $type_name = check_plain($type->type);
    $permissions += array(
      "edit any $type_name micronews" => array(
        'title' => t('%type_name: Edit any micronews', array('%type_name' => $type->label)),
      ),
      "view any $type_name micronews" => array(
        'title' => t('%type_name: View any micronews', array('%type_name' => $type->label)),
      ),
    );
  }
  return $permissions;  
}


/**
 * Determines whether the given user has access to a micronews.
 *
 * @param $op
 *   The operation being performed. One of 'view', 'update', 'create', 'delete'
 *   or just 'edit' (being the same as 'create' or 'update').
 * @param $micronews
 *   Optionally a micronews or a micronews type to check access for. If nothing is
 *   given, access for all micronews is determined.
 * @param $account
 *   The user to check for. Leave it to NULL to check for the global user.
 * @return boolean
 *   Whether access is allowed or not.
 */
function micronews_access($op, $micronews = NULL, $account = NULL) {
  if (user_access('administer micronews', $account)) {
    return TRUE;
  }
  if (isset($micronews) && $type_name = $micronews->type) {
    $op = ($op == 'view') ? 'view' : 'edit';
    if (user_access("$op any $type_name micronews", $account)) {
      return TRUE;
    }
  }
  return FALSE;
}


/**
 * Access callback for the entity API.
 */
function micronews_type_access($op, $type = NULL, $account = NULL) {
  return user_access('administer micronews types', $account);
}


/**
 * Gets an array of all micronews types, keyed by the type name.
 *
 * @param $type_name
 *   If set, the type with the given name is returned.
 * @return micronewsType[]
 *   Depending whether $type isset, an array of micronews types or a single one.
 */
function micronews_get_types($type_name = NULL) {
  // entity_load will get the Entity controller for our micronews entity and call the load
  // function of that object - we are loading entities by name here.
  $types = entity_load_multiple_by_name('micronews_type', isset($type_name) ? array($type_name) : FALSE);
  return isset($type_name) ? reset($types) : $types;
}


/**
 * Menu argument loader; Load a micronews type by string.
 *
 * @param $type
 *   The machine-readable name of a micronews type to load.
 * @return
 *   A micronews type array or FALSE if $type does not exist.
 */
function micronews_type_load($type) {
  return micronews_get_types($type);
}


/**
 * Fetch a micronews object. Make sure that the wildcard you choose 
 * in the micronews entity definition fits the function name here.
 *
 * @param $micronews_id
 *   Integer specifying the micronews id.
 * @param $reset
 *   A boolean indicating that the internal cache should be reset.
 * @return
 *   A fully-loaded $micronews object or FALSE if it cannot be loaded.
 *
 * @see micronews_load_multiple()
 */
function micronews_load($micronews_id, $reset = FALSE) {
  $micronews = micronews_load_multiple(array($micronews_id), array(), $reset);
  return reset($micronews);
}


/**
 * Load multiple micronews based on certain conditions.
 *
 * @param $micronews_ids
 *   An array of micronews IDs.
 * @param $conditions
 *   An array of conditions to match against the {micronews} table.
 * @param $reset
 *   A boolean indicating that the internal cache should be reset.
 * @return
 *   An array of micronews objects, indexed by micronews_id.
 *
 * @see entity_load()
 * @see micronews_load()
 */
function micronews_load_multiple($micronews_ids = array(), $conditions = array(), $reset = FALSE) {
  return entity_load('micronews', $micronews_ids, $conditions, $reset);
}


/**
 * Deletes a micronews.
 */
function micronews_delete(micronews $micronews) {
  $micronews->delete();
}


/**
 * Delete multiple micronews.
 *
 * @param $micronews_ids
 *   An array of micronews IDs.
 */
function micronews_delete_multiple(array $micronews_ids) {
  entity_get_controller('micronews')->delete($micronews_ids);
}


/**
 * Create a micronews object.
 */
function micronews_create($values = array()) {
  return entity_get_controller('micronews')->create($values);
}


/**
 * Saves a micronews to the database.
 *
 * @param $micronews
 *   The micronews object.
 */
function micronews_save(micronews $micronews) {
  return $micronews->save();
}


/**
 * Saves a micronews type to the db.
 */
function micronews_type_save(micronewsType $type) {
  $type->save();
}


/**
 * Deletes a micronews type from the db.
 */
function micronews_type_delete(micronewsType $type) {
  $type->delete();
}


/**
 * URI callback for micronews
 */
function micronews_uri(micronews $micronews){
  return array(
    'path' => 'micronews/' . $micronews->micronews_id,
  );
}


/**
 * Menu title callback for showing individual entities
 */
function micronews_page_title(micronews $micronews){
  return $micronews->name;
}


/**
 * Sets up content to show an individual micronews
 * @todo - get rid of drupal_set_title();
 */
function micronews_page_view($micronews, $view_mode = 'full') {    
  $controller = entity_get_controller('micronews');  
  $content = $controller->view(array($micronews->micronews_id => $micronews));
  drupal_set_title($micronews->name);
  return $content;
}


/**
 * Implements hook_views_api().
 */
function micronews_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'micronews') . '/views',
  );
}


/**
 * Implement hook_theme().
 */
function micronews_theme() {
  return array(
    'micronews_add_list' => array(
      'variables' => array('content' => array()),
      'file' => 'micronews.admin.inc',
    ),
    'micronews' => array(
      'render element' => 'elements',
      'template' => 'micronews',
    ),
   'micronews_sample_data' => array(
      'variables' => array('micronews_sample_data', 'micronews' => NULL),
      'template' => 'micronews-sample-data',
    ),


  );
}  


/**
 * Implements hook_menu_local_tasks_alter().
 */
function micronews_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  // Add action link 'admin/structure/micronews/add' on 'admin/structure/micronews'.
  if ($root_path == 'admin/content/micronews') {
    $item = menu_get_item('admin/content/micronews/add');
    if ($item['access']) {
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
    }
  }
}


/**
 * The class used for micronews entities
 */
class micronews extends Entity {
  
  public function __construct($values = array()) {
    parent::__construct($values, 'micronews');
  }

  protected function defaultLabel() {
    return $this->name;
  }

  protected function defaultUri() {
    return array('path' => 'micronews/' . $this->micronews_id);
  }
  
  
}


/**
 * The class used for micronews type entities
 */
class micronewsType extends Entity {
  
  public $type;
  public $label;
  
  public function __construct($values = array()) {
    parent::__construct($values, 'micronews_type');
  }
  
}


/**
 * The Controller for micronews entities
 */
class micronewsController extends EntityAPIController {
  public function __construct($entityType) {
    parent::__construct($entityType);
  }


  /**
   * Create a micronews - we first set up the values that are specific
   * to our micronews schema but then also go through the EntityAPIController
   * function.
   * 
   * @param $type
   *   The machine-readable type of the micronews.
   *
   * @return
   *   A micronews object with all default fields initialized.
   */
  public function create(array $values = array()) {
    // Add values that are specific to our micronews
    $values += array( 
      'micronews_id' => '',
      'is_new' => TRUE,
      'title' => '',
      'created' => '',
      'changed' => '',
      'data' => '',
    );
    
    $micronews = parent::create($values);
    return $micronews;
  }
  
  /**
   * Overriding the buldContent function to add entity specific fields
   */
  public function buildContent($entity, $view_mode = 'full', $langcode = NULL, $content = array()) {
    $content = parent::buildContent($entity, $view_mode, $langcode, $content);
    $content['micronews_sample_data'] =  array(
      '#markup' => theme('micronews_sample_data', array('micronews_sample_data' => check_plain($entity->data['sample_data']), 'micronews' => $entity)),
    );

    return $content;
  }
  
}


/**
 * The Controller for micronews entities
 */
class micronewsTypeController extends EntityAPIControllerExportable {
  public function __construct($entityType) {
    parent::__construct($entityType);
  }
  
   /**
   * Create a micronews type - we first set up the values that are specific
   * to our micronews type schema but then also go through the EntityAPIController
   * function.
   * 
   * @param $type
   *   The machine-readable type of the micronews.
   *
   * @return
   *   A micronews type object with all default fields initialized.
   */
  public function create(array $values = array()) {
    // Add values that are specific to our micronews
    $values += array( 
      'id' => '',
      'is_new' => TRUE,
      'data' => '',
    );
    $micronews_type = parent::create($values);
    return $micronews_type;
  }

}

// function micronews_menu_alter() {
//   $items['admin/content/micronews/add/microcomments'] = array(
//     'modal' => TRUE, // This line is where the magic happens.
//   );
// }

// function  micronews_alter_menu_alter(&$items) {
//   $items['node/add/article']['modal'] = TRUE;
// }