<?php

/**
 * @file
 * Administrative interface for creating/updating Micro types
 */

/**
 * Implements hook_menu().
 */
function micro_admin_menu() {
  $items['admin/content/micro'] = array(
    'title' => 'Micro',
    'description' => 'List and edit micro items.',
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('micro_admin'),
    'access arguments' => array('administer micro types'),
    'type' => MENU_LOCAL_TASK | MENU_NORMAL_ITEM,
    'file' => 'micro_admin.ui.inc',
  );
  $items['admin/content/micro/add'] = array(
    'title' => 'Add micro item',
    'page callback' => 'drupal_goto',
    'page arguments' => array('micro/add'),
    'access callback' => '_micro_add_access',
    'type' => MENU_LOCAL_ACTION,
  );
  $items['admin/structure/micro'] = array(
    'title' => 'Micro types',
    'description' => 'Manage content types, including default status, front page promotion, comment settings, etc.',
    'page callback' => 'micro_overview_types',
    'access arguments' => array('administer content types'),
    'file' => 'micro_admin.ui.inc',
  );
  $items['admin/structure/micro/list'] = array(
    'title' => 'List',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['admin/structure/micro/add'] = array(
    'title' => 'Add micro type',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('micro_type_form'),
    'access arguments' => array('administer micro types'),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'micro_admin.ui.inc',
  );
  $items['admin/structure/micro/manage/%micro_type'] = array(
    'title' => 'Edit micro type',
    'title callback' => 'micro_type_page_title',
    'title arguments' => array(4),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('micro_type_form', 4),
    'access arguments' => array('administer micro types'),
    'file' => 'micro_admin.ui.inc',
  );
  $items['admin/structure/micro/manage/%micro_type/edit'] = array(
    'title' => 'Edit micro type',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/structure/micro/manage/%micro_type/delete'] = array(
    'title' => 'Delete micro type',
    'page arguments' => array('micro_type_delete_confirm', 4),
    'access arguments' => array('administer micro types'),
    'file' => 'micro_admin.ui.inc',
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function micro_admin_theme() {
  return array(
    'micro_admin_overview' => array(
      'variables' => array('name' => NULL, 'type' => NULL),
      'file' => 'micro_admin.ui.inc',
    ),
  );
}

/**
 * Implements hook_permission().
 */
function micro_admin_permission() {
  $permissions = array(
    'administer micro types' =>  array(
      'title' => t('Administer micro types'),
      'description' => t('Create and delete fields for micro types.'),
    ),
  );

  return $permissions;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function micro_admin_form_field_ui_field_edit_form_alter(&$form, &$form_state, $form_id) {
  // Micro reference settings.
  module_load_include('inc', 'micro_admin', 'micro_admin.ui');
  $form['instance']['micro'] = micro_admin_field_micro_settings_form($form['#field'], $form['#instance']);
}

/**
* Implements hook_micro_operations().
*/
function micro_admin_micro_operations() {
  $operations = array(
    'delete' => array(
      'label' => t('Delete selected content'),
      'callback' => NULL,
    ),
  );
  return $operations;
} 
